// click event - an interaction when a user clicks on a soecifit element
//               we can respond to clicks by passing 
//               a callback to the OnClick event handler

function Button() {

  

  const handleClick = (e) => e.target.textContent ="OUCH😫"; //event hander

  // let count = 0;
  // const handleClick = (name) => {
      //if(count<3){
       // count++;
       // console.log(`${name} you clicked me ${count} times`);
      // }
      // else{
      //  console.log(`${name} stop clicking me`);
      // }
  // };

  const handleClick2 = (name) => console.log(`${name} stop clicking me`); // `` Template string

    //External CSS great for global styles
  const styles = { //Inline CSS Styles. greate for small components with minimal stylying
        
          backgroundColor: "hsl(200, 100%, 50%)",
          color: "white",
          padding: "10px 20px",
          borderRadius: "5px",
          border: "none",
          cursor: "pointer",
        }
    

    return(<button style={styles} onClick={(e) => handleClick(e)}>Click Me! 😊</button>);
    // return(<button style={styles} onClick={() => handleClick("Eric")}>Click Me! 😊</button>); 
 
    //Modules avoid naming conflicts since a unique class is generated by hashing algorithm
    //modules is greate for individual components that have unique styles 
}

export default Button